# Generated by Django 3.2.3 on 2022-06-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.DecimalField(decimal_places=0, max_digits=12)),
                ('non_refundable_amount', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('refundable_amount', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('rental', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('purpose', models.CharField(max_length=50, null=True)),
                ('work_place', models.CharField(max_length=50, null=True)),
                ('first_arrival_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('source_account_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('Cash', 'Cash'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI')], default='Cash', max_length=20)),
                ('destination_account_name', models.CharField(max_length=200)),
                ('destination_type', models.CharField(choices=[('Cash', 'Cash'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI')], default='Cash', max_length=20)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('4 Wheeler', '4 Wheeler'), ('2 Wheeler', '2 Wheeler')], default='2 Wheeler', max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Online', 'Online'), ('Nearby Shop', 'Nearby Shop'), ('Market Shop', 'Market Shop'), ('Individual', 'Individual'), ('Others', 'Others')], default='Individual', max_length=20)),
                ('desciption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField(auto_created=True)),
                ('from_date', models.DateField(auto_created=True)),
                ('stay_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], default='Monthly', max_length=20)),
                ('accomodation_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], default='Single', max_length=20)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.guest')),
                ('payments', models.ManyToManyField(to='pg.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_type', models.CharField(choices=[('Driving License', 'Driving License'), ('Aadhar Card', 'Aadhar Card')], default='Aadhar Card', max_length=20)),
                ('identity_proof', models.FileField(upload_to='static/data/guest/identity/')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.guest')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pg.vehicle'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('type', models.CharField(choices=[('House Keeping', 'House Keeping'), ('Room Accessory', 'Room Accessory'), ('PG Accessory', 'PG Accessory'), ('Eletricity', 'Eletricity'), ('Plumbing', 'Plumbing'), ('Others', 'Others')], default='House Keeping', max_length=20)),
                ('frequency', models.CharField(choices=[('Recurring', 'Recurring'), ('One Time', 'One Time')], default='Recurring', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI')], default='Cash', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refundable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.guest')),
                ('payments', models.ManyToManyField(to='pg.Payment')),
            ],
        ),
    ]
