# Generated by Django 4.0.4 on 2022-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identify_type',
            field=models.CharField(choices=[('Driving License', 'Driving License'), ('Aadhar Card', 'Aadhar Card')], default='Aadhar Card', max_length=20),
        ),
    ]
