# Generated by Django 4.0.4 on 2022-06-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_alter_identity_identity_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='identity_proof_content',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identify_type',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Driving License', 'Driving License')], default='Aadhar Card', max_length=20),
        ),
    ]
