# Generated by Django 4.0.4 on 2022-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0005_alter_guest_non_refundable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='identity_proof_content',
        ),
        migrations.AlterField(
            model_name='identity',
            name='identify_type',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Driving License', 'Driving License')], default='Aadhar Card', max_length=20),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_proof',
            field=models.FileField(upload_to='data/guest/identity'),
        ),
    ]
