# Generated by Django 4.0.4 on 2022-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_remove_identity_identity_proof_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_proof',
            field=models.FileField(upload_to='static/data/guest/identity/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Nearby Shop', 'Nearby Shop'), ('Market Shop', 'Market Shop'), ('Individual', 'Individual'), ('Others', 'Others')], default='Individual', max_length=20),
        ),
    ]
