# Generated by Django 4.0.4 on 2022-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_alter_identity_identity_proof_alter_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('4 Wheeler', '4 Wheeler'), ('2 Wheeler', '2 Wheeler')], default='2 Wheeler', max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='identity',
            name='identify_type',
            field=models.CharField(choices=[('Driving License', 'Driving License'), ('Aadhar Card', 'Aadhar Card')], default='Aadhar Card', max_length=20),
        ),
    ]
